package com.portfoliotracker.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Represents one day's closing price for a symbol.
 *
 * In this project prices are generated by a simple simulated random-walk
 * feed (see MarketPriceService) so the project is self-contained and does
 * not depend on a paid external market-data API. In a real system this
 * table would instead be populated by an integration with a provider such
 * as Alpha Vantage, Twelve Data, or IEX Cloud.
 */
@Entity
@Table(name = "market_prices", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"symbol", "priceDate"})
}, indexes = {
        @Index(name = "idx_market_price_symbol_date", columnList = "symbol, priceDate")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MarketPrice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 15)
    private String symbol;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal closePrice;

    @Column(nullable = false)
    private LocalDate priceDate;
}
